
app = "freshrss" # Change this, should be unique
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "freshrss/freshrss:1.20.1"

[env]
  CRON_MIN='*/20'
# Published port for development or local use (optional)
    PUBLISHED_PORT=8080
# =========================================
# For automatic FreshRSS install (optional)
# =========================================
    ADMIN_PASSWORD='freshrss'
    ADMIN_API_PASSWORD='freshrss'
# Address at which the FreshRSS instance will be reachable:
# Database server (not relevant if using default SQLite)
# Use the name of the Docker container if running on the same machine
    DB_HOST='freshrss-db'
# ===========================================================
# Database credentials (not relevant if using default SQLite)
# ===========================================================
# Database to use
    DB_BASE='freshrss'
# User in the freshrss database
    DB_USER='freshrss'
# Password for the defined user
    DB_PASSWORD='freshrss'

[mounts]
  source="freshrss_data"
  destination="/var/www/FreshRSS/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
